---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
    tier: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress # Create service selector labels here
    tier: mysql
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-mysql
data:
  database: wordpress # create non-sensative data attributes
  user: wordpress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
    tier: mysql
spec:
  selector: # Create app label selectors here
    matchLabels:
      app: wordpress
      tier: mysql
  template:
    metadata: # Create metadata labels here
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
        # mount non-sensitive environment vars from configmap
        # MYSQL_DATABASE | MYSQL_USER
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: wordpress-mysql
              key: database
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: wordpress-mysql
              key: user
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database
              key: root-password
        - name: MYSQL_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: database
              key: user-password
        ports:
        # mount sensitive environment vars from secret
        # MYSQL_ROOT_PASSWORD | MYSQL_PASSWORD
        - containerPort: 3306
          name: mysql
        volumeMounts:
        # define volume mounts here, be sure to reference
        # the PVC in your container spec
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
##
# Create persistent volume claim here
##
